version: '3'
services:
    messaging:
        image: 'rabbitmq:3-management'
        ports:
            - 15672:15672
    mysql:
        image: 'mysql'
        # README: https://stackoverflow.com/questions/50557234/authentication-plugin-caching-sha2-password-is-not-supported
        # README: https://hub.docker.com/_/mysql
        #command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_PASSWORD: changeme
            MYSQL_DATABASE: testapp
        # You only need this if you are accessing your database
        # outside of the docker network
        ports:
          - "3308:3306"
    admin:    
        image: adminer    
        ports:      
         - "8080:8080"
    front_end:
        build: ./front_end
        ports:
            - 5000:5000
    hello:
        build: './Backend/Hello'

    recieve:
        build: './Backend/Receive'

    backend_sql_test:
        build: './Backend/SQL'
    
