version: '3'
services:
    messaging:
        image: 'rabbitmq:3-management'
        ports:
            - 15672:15672
    mysql:
        image: 'mysql'
        environment:
            MYSQL_ROOT_PASSWORD: changeme
            MYSQL_DATABASE: testapp
        ports:
          - "3308:3306"
    admin:    
        image: adminer    
        ports:      
         - "8080:8080"
    front_end:
        build: ./front_end
        ports:
            - 5000:5000
    hello:
        build: './Backend/Hello'

    recieve:
        build: './Backend/Receive'
    
